export const DEFAULT_ROLES = [
  {
    name: 'ADMIN',
    description: 'Has unrestricted access to all system features, settings, and data management',
    permissions: [
      'user:create',
      'user:display',
      'user:update',
      'user:archive',
      'role:create',
      'role:display',
      'role:update',
      'role:archive',
      'permission:create',
      'permission:display',
      'permission:update',
      'permission:archive',
      'occupation:create',
      'occupation:display',
      'occupation:update',
      'occupation:archive',
      'currency:create',
      'currency:display',
      'currency:update',
      'currency:archive',
      'timezone:create',
      'timezone:display',
      'timezone:update',
      'timezone:archive',
      'country:create',
      'country:display',
      'country:update',
      'country:archive',
    ],
  },

  {
    name: 'USER',
    description: 'Has limited access to specific features and data based on assigned permissions',
    permissions: ['dashboard:display'],
  },
];
